openapi: 3.0.0
info:
  version: 0.0-oas3
  title: movieSales
  description: >-
      A service to predict movie theater ticket sales.

paths:
  /tickets/<price>/<time>/<capacity>/<month>/<day>/<quarter>:
    post:
      tags: 
        - Tickets          
      summary: input price, time, capacity, month, day, quarter to receive prediction of ticket sales
      operationId: prediction.ticketSales
      description: Returns prediction for ticket sales given inputs
      parameters:

        - name: price
          in: query
          description: Ticket Price            
          required: true
          schema:
            type: integer
            
        - name: time
          in: query
          description: Movie Showtime, Hourly Single Digit  
          required: true
          schema:
            type: integer
            
        - name: capacity
          in: query
          description: Theater Capacity            
          required: true
          schema:
            type: integer
            
        - name: month
          in: query
          description: Show Month           
          required: true
          schema:
            type: integer
            
        - name: day
          in: query
          description: Show Day           
          required: true
          schema:
            type: integer
            
        - name: quarter
          in: query
          description: quarter of year      
          required: true
          schema:
            type: integer
            
      responses:
        '200':
          description: Predicted Ticket Sales
        '405':
          description: Invalid Input

  /totalsale/<price>/<time>/<capacity>/<month>/<day>/<quarter>:
      post:
        tags: 
          - Sales              
        summary: input price, time, capacity, month, day, quarter to receive prediction of total sales
        operationId: prediction.totalsales
        description: Returns prediction for total sales given inputs

        parameters:
        - name: price
          in: query
          description: Ticket Price            
          required: true
          schema:
            type: integer
            
        - name: time
          in: query
          description: Movie Showtime, Hourly Single Digit  
          required: true
          schema:
            type: integer
            
        - name: capacity
          in: query
          description: Theater Capacity            
          required: true
          schema:
            type: integer
            
        - name: month
          in: query
          description: Show Month           
          required: true
          schema:
            type: integer
            
        - name: day
          in: query
          description: Show Day           
          required: true
          schema:
            type: integer
            
        - name: quarter
          in: query
          description: quarter of year      
          required: true
          schema:
            type: integer

        responses:
          '200':
            description: Predicted Ticket Sales
          '405':
            description: Invalid Input



servers:
  - url: 'http://localhost:8080/movieSalesPrediction'
