openapi: 3.0.0
info:
  version: 0.0-oas3
  title: movieSales
  description: >-
      A service to predict movie theater ticket sales.

paths:
  /list:
    get:
      tags:
        - List
      summary: return a list of possible operations
      operationId: pyDir.prediction.list
      description: Returns list of possible operations for user and inputs
      responses:
        '200':
          description: List of functionality
        '405':
          description: Invalid Input

  /tickets/{price}/{time}/{capacity}/{month}/{day}:
    get:
      tags: 
        - Tickets          
      summary: input price, time, capacity, month, day to receive prediction of ticket sales
      operationId: pyDir.prediction.ticketSales
      description: Returns prediction for ticket sales given inputs
      parameters:

        - name: price
          in: path
          description: Ticket Price            
          required: true
          schema:
            type: integer
            
        - name: time
          in: path
          description: Movie Showtime, Hourly Single Digit  
          required: true
          schema:
            type: integer
            
        - name: capacity
          in: path
          description: Theater Capacity            
          required: true
          schema:
            type: integer
            
        - name: month
          in: path
          description: Show Month           
          required: true
          schema:
            type: integer
            
        - name: day
          in: path
          description: Show Day           
          required: true
          schema:
            type: integer
            
      responses:
        '200':
          description: Predicted Ticket Sales
        '405':
          description: Invalid Input

  /totalsale/{price}/{time}/{capacity}/{month}/{day}:
      get:
        tags: 
          - Sales              
        summary: input price, time, capacity, month, day to receive prediction of total sales
        operationId: pyDir.prediction.totalsales
        description: Returns prediction for total sales given inputs

        parameters:
        - name: price
          in: path
          description: Ticket Price            
          required: true
          schema:
            type: integer
            
        - name: time
          in: path
          description: Movie Showtime, Hourly Single Digit  
          required: true
          schema:
            type: integer
            
        - name: capacity
          in: path
          description: Theater Capacity            
          required: true
          schema:
            type: integer
            
        - name: month
          in: path
          description: Show Month           
          required: true
          schema:
            type: integer
            
        - name: day
          in: path
          description: Show Day           
          required: true
          schema:
            type: integer
            
        responses:
          '200':
            description: Predicted Ticket Sales
          '405':
            description: Invalid Input



servers:
  - url: 'http://localhost:8080'
